language: python
python:
  - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip

install:
  - pip install urllib3==1.26.15
  - pip install -U platformio
  - pio update

before_script:
  - |
    if [[ $TRAVIS_TAG =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
      export MAJOR_VERSION=${BASH_REMATCH[1]}
      export MINOR_VERSION=${BASH_REMATCH[2]}
      export PATCH_VERSION=${BASH_REMATCH[3]}
      echo "Setting MAJOR to $MAJOR_VERSION"
      echo "Setting MINOR to $MINOR_VERSION"
      echo "Setting PATCH to $PATCH_VERSION"
    else
      echo "Tag does not match version pattern"
      exit 1
    fi

script:
  - pio --version
  - pio run
  - sha256sum .pio/build/ATtiny1616/firmware.hex > .pio/build/ATtiny1616/firmware.hex.sha256

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ".pio/build/ATtiny1616/firmware.hex"
    - ".pio/build/ATtiny1616/firmware.hex.sha256"
  skip_cleanup: true
  on:
    tags: true
