language: python
python:
  - "3.9"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip

install:
  - pip install urllib3==1.26.15
  - pip install -U platformio
  - pio update

script:
  - pio run
  - sha256sum .pio/build/ATtiny1616/firmware.hex > .pio/build/ATtiny1616/firmware.hex.sha256

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - ".pio/build/ATtiny1616/firmware.hex"
    - ".pio/build/ATtiny1616/firmware.hex.sha256"
  skip_cleanup: true
  on:
    tags: true
